[package]
org = "dhananjaya"
name = "simpletl"
version = "0.1.0"

[build-options]
observabilityIncluded = false

[[platform.java11.dependency]]
artifactId = "mysql-connector-java"
version = "8.0.17"
path = "../binary_dependencies/mysql-connector-java-8.0.23.jar"
groupId = "mysql"